spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cache:
    redis:
      time-to-live: 1800000

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health