spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/projeto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000


  rabbitmq:
    queue:
      pedido-concluido: pedidos.concluido
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin123!}
    connection-timeout: 5000


  cache:
    redis:
      time-to-live: 1800000
      host: localhost
      port: 6379


  mail:
    host: ${SMTP_HOST:}
    username: ${SMTP_USER:}
    password: ${SMTP_PASSWORD:}
    port: ${SMTP_PORT:}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:false}
          starttls.enable: ${SMTP_STARTTLS:false}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,env,beans
  endpoint:
    health:
      show-details: always
      db:
        enabled: true
      redis:
        enabled: true
      rabbit:
        enabled: true


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.empresa: DEBUG
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"