spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 2000

  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          max-interval: 10000ms
          multiplier: 2.0
        concurrency: 3
        max-concurrency: 10
        prefetch: 10
        default-requeue-rejected: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cache:
    redis:
      time-to-live: 1800000

server:
  shutdown: graceful
mail:
  host: smtp.example.com
  username: seu-email@example.com
  password: sua-senha
  port: 587
  properties:
    mail:
      smtp:
        auth: true
        starttls:
         enable: true

management:
  endpoints:
    web:
      exposure:
        include: health
